# Generated by Django 4.2.23 on 2025-07-03 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('daily_budget', models.FloatField()),
                ('monthly_budget', models.FloatField()),
                ('current_daily_spend', models.FloatField(default=0.0)),
                ('current_monthly_spend', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('total_spend_today', models.FloatField(default=0.0)),
                ('total_spend_month', models.FloatField(default=0.0)),
                ('allowed_start_hour', models.IntegerField(default=0)),
                ('allowed_end_hour', models.IntegerField(default=23)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.brand')),
            ],
        ),
        migrations.CreateModel(
            name='SpendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.campaign')),
            ],
        ),
    ]
